---
title: "AIS Data IDs"
output: html_document
---

# START
```{r}
library(tidyverse)
options(dplyr.summarise.inform = FALSE)
```

```{r}
min.na <- function(x){
  ifelse(all(is.na(x)), NA_real_, min(x, na.rm = TRUE))
}

max.na <- function(x){
  ifelse(all(is.na(x), NA_real_, max(x, na.rm = TRUE)))
}
```


```{r}
ids_df <- read_csv("data/ais_ids.csv",
                   col_types = "innci") %>% 
  rename(Obs.Count = name...5,
         name = name...4)

load("data/All_join.Rda")
```

```{r}
ids_df |> distinct(mmsi) |> nrow()
```

How many mmsi-imo combinations?
```{r}
ids_df |> 
  group_by(mmsi, imo) |> 
  summarise(Obs.Count = sum(Obs.Count))
```

How many mmsi associated with each imo?
```{r}
ids_df |> 
  filter(imo != 0) |> 
  group_by(mmsi, imo) |> 
  summarise(Obs.Count = sum(Obs.Count)) |> 
  filter(Obs.Count > 10) |> 
  group_by(mmsi) |> 
  mutate(n = n()) |> 
  filter(n == 2) |>
  arrange(mmsi)
```

```{r}
ids_df |> 
  
```



```{r}
ids_df |> 
  filter(Obs.Count > 2) |> 
  ggplot(aes(x = Obs.Count)) +
  geom_histogram()
```



```{r}
if(
  0 != ids_df %>% 
    mutate(imo_decimals = imo %% 1) %>% 
    filter(imo_decimals > 0) %>% 
    nrow() |
  0 != ids_df %>% 
    mutate(length_decimals = length %% 1) %>% 
    filter(length_decimals > 0) %>% 
    nrow()
){stop('Either imo or length has non-zero decimal digits.')}

```

```{r}
ids_df |>
  arrange(mmsi)
```


```{r}
ids_df |> 
  filter(imo > 0) |> 
  group_by(mmsi, imo) |> 
  summarise(Obs.Count = sum(Obs.Count)) |> 
  ungroup() |> 
  count(imo)
  # count(n)
  # arrange(desc(n))
  # ggplot(aes(x=n)) +
  # geom_histogram()
```

Verify 
```{r}
IMO_checksum <- function(imo){
  digits_sum = 0
  n_digits = nchar(imo)
  if(n_digits > 7){
    valid = FALSE
  }else{
    imo = str_pad(imo, width = 7, side = 'left', pad = '0')
    for(i in 1:6){
      digits_sum = digits_sum + (8-i)*as.integer(str_sub(imo, i, i))
    }
    digits_sum = as.character(digits_sum)
    valid = str_sub(imo, 7, 7) == str_sub(digits_sum, -1)
  }
  return(valid)
}
```

Check invalid
```{r}
IMO_checksum(9834203)
```

Check valid (example from https://en.wikipedia.org/wiki/IMO_number)
```{r}
IMO_checksum(9074729)
```


```{r}
ids_df |> 
  rowwise() |> 
  mutate(Valid.IMO = IMO_checksum(imo))
```



# END