---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)
print(getwd())
```

```{r}
datapath = 'data'
```

```{r}
old <- read_csv(file.path(datapath, 'df_ml.csv'))
# old <- read_csv(file.path(datapath, 'AIS_speed_EEZ_EU_yearly_state_minebad.csv'))
```

```{r}
colnames(old)[old |> colnames() |> str_detect('distance')]
```

```{r}
mine = read_csv(file.path(datapath, 'AIS_speed_EEZ_EU_yearly_stats.csv')) |> 
  select(mmsi, year, distance_sum, FC_sum)
colnames(mine)
```

```{r}
mine
```

```{r}
load(file.path('/home/apeters/Documents/PhD/ShippingEmissions/src/data','MRV.Rda'))

MRV_df |> 
  colnames()
```

```{r}
load(file.path('/home/apeters/Documents/PhD/ShippingEmissions/src/data', 'bulkers_WFR.Rda'))
# colnames(bulkers_df)
```

```{r}
MRV_df <- MRV_df |> 
  select(imo.number, reporting.period, EU.distance, total.fc) |> 
  mutate(IMO.Number = as.integer(imo.number),
         .after = 'imo.number',
         .keep = 'unused') |> 
  left_join(bulkers_df |> select(IMO.Number, mmsi = MMSI, Built.Year),
            by = c('IMO.Number')) |> 
  mutate(year = as.numeric(levels(reporting.period)[reporting.period]),
         .keep = 'unused')
```

```{r}
mine <- mine |> 
  left_join(MRV_df,
            by = c('mmsi', 'year')) |> 
  drop_na(IMO.Number)
```

```{r}
mine
```

```{r}
mine |> 
  group_by(year) |> 
  count()
```

# Relative distance

```{r}
mine |> 
  bind_rows(old, .id = 'ID') |> 
  mutate(ID = factor(ID, levels = c(1,2), labels = c('mine', 'old'))) |> 
  mutate(diff = EU.distance - distance_sum) |> 
  filter(abs(diff/EU.distance) < 1) |> 
  ggplot(aes(x = diff/EU.distance*100, fill = factor(year))) +
  geom_histogram(binwidth = 1) +
  facet_grid(year ~ ID) +
  geom_vline(xintercept = c(-10, 10))
```

```{r}
old |>
  mutate(diff = abs(EU.distance - distance_sum)) |> 
  filter((diff - distance_difference) > 0.0001) |> 
  select(mmsi, diff, distance_difference)
  # summarise(all(diff == distance_difference))
  # summarise(max(distance_difference))
```

```{r}
mine |> 
  mutate(diff = EU.distance - distance_sum,
         good = abs(diff) <= 500) |> 
  group_by(good) |> 
  count()
```

Absolute distance

```{r}
mine |> 
  bind_rows(old, .id = 'ID') |> 
  mutate(ID = factor(ID, levels = c(1,2), labels = c('mine', 'old'))) |> 
  mutate(diff = EU.distance - distance_sum) |> 
  filter(abs(diff) <= 500) |>
  ggplot(aes(x = diff, fill = factor(year))) +
  geom_histogram(binwidth = 1) +
  facet_grid(year ~ ID) +
  geom_vline(xintercept = c(-500, 500))
```

```{r}
quantile(mine$FC_sum, probs = 0.99)
```

```{r}
mine |> 
  bind_rows(old, .id = 'ID') |> 
  mutate(ID = factor(ID, levels = c(1,2), labels = c('mine', 'old'))) %>%
  filter(FC_sum < quantile(.$FC_sum, probs = 0.96)) |> 
  ggplot(aes(x = FC_sum, fill = ID)) +
  geom_histogram(position = 'identity', alpha = 0.5) +
  # facet_grid(year ~ ID)
  facet_wrap(~factor(year))
```

```{r}
mine |> 
  mutate(diff = EU.distance - distance_sum) |> 
  mutate(close = abs(diff/EU.distance)*100 < 10) |> 
  group_by(year, close) |> 
  count()
```

```{r}
old |> 
  select(contains('dist'))
```

```{r}
old |> 
  mutate(diff = EU.distance - distance_sum) |> 
  ggplot(aes(x = diff/EU.distance*100)) +
  geom_histogram(binwidth = 1) +
  geom_vline(xintercept = c(-10,10))
```

```{r}
old |> 
  ggplot(aes(x = distance_difference/EU.distance * 100)) +
  geom_histogram(binwidth = 0.1)
```

```{r}
old |> 
  ggplot(aes(x = distance_difference)) +
  geom_histogram()
```

```{r}
old <- old |> 
  select(mmsi, year, distance_sum, FC_sum, EU.distance)

old
```

```{r}
compare <- full_join(mine, old, by = c('mmsi', 'year'),
                     suffix = c('.mine', '.old'))
```

```{r}
compare |> 
  mutate(notin.mine = is.na(FC_sum.mine),
         notin.old =  is.na(FC_sum.old)) |> 
  # group_by(year) |> 
  count(notin.mine, notin.old)
```

```{r}
compare |> 
  mutate(good.mine = abs(distance_sum.mine-EU.distance.mine) < 500,
         good.old =  abs(distance_sum.old-EU.distance.old) <500) |> 
  # group_by(year) |> 
  count(good.mine, good.old)
```

With fixed implied speed version: Lost 778 ships, gained 128 new ones, 494 in common

Which ships lost?

```{r}
compare |> 
  filter()
```

```{r}
compare |> 
  select(mmsi, year, starts_with('distance_sum'), starts_with('FC')) |> 
  mutate(distance.diff.pct = (distance_sum.mine/distance_sum.old - 1)*100,
         FC.diff.pct = (FC_sum.mine/FC_sum.old - 1)*100) |> 
  ggplot(aes(x = FC.diff.pct, fill = year)) +
  geom_histogram() +#binwidth = 1)
  xlim(-100, 2000)
```

```{r}
compare |> 
  select(mmsi, year, starts_with('distance_sum'), starts_with('EU.distance')) |> 
  mutate(EU.distance = coalesce(EU.distance.mine, EU.distance.old)) |> 
  select(mmsi, year, distance_sum.mine, distance_sum.old, EU.distance) |> 
  pivot_longer(c(-mmsi,-year)) |> 
  ggplot(aes(x = value, fill = name)) +
  geom_histogram(position = 'identity', alpha = 0.5) +
  facet_wrap(~year)
```

```{r}
compare |> 
  select(mmsi, year, starts_with('distance_sum'), starts_with('EU.distance')) |> 
  mutate(EU.distance = coalesce(EU.distance.mine, EU.distance.old)) |> 
  mutate(error.mine = distance_sum.mine - EU.distance,
         error.old = distance_sum.old - EU.distance) |> 
  select(mmsi, year, error.mine, error.old) |> 
  pivot_longer(c(-mmsi,-year)) |> 
  ggplot(aes(x = value, fill = name)) +
  geom_histogram(position = 'identity', alpha = 0.5) +
  facet_wrap(~year) +
  xlim(-500, 500)
```

```{r}
df_ml <- mine |> 
  mutate(FC_sum = FC_sum/1e6,
         age = year - Built.Year,
         residual = log(1 + total.fc) - log(1 + FC_sum),
         distance_difference = abs(distance_sum - EU.distance),
         distance_difference_sign = distance_sum - EU.distance) |> 
  filter(distance_difference <= 500)
```

```{r}
FC_mean <- mean(df_ml$FC_sum)
FC_sd <- sd(df_ml$FC_sum)

df_ml |> 
  filter(between(FC_sum, FC_mean-FC_sd, FC_mean+FC_sd)) |> 
  ggplot(aes(x = total.fc, y = FC_sum)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_abline(slope = 1, intercept = 0) +
  ylim(NA, 10000) +
  labs(x = 'Reported FC',
         y = 'Estimated FC')

df_ml |> 
  filter(between(FC_sum, FC_mean-FC_sd, FC_mean+FC_sd)) |> 
  ggplot(aes(x = log(total.fc), y = log(FC_sum))) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_abline(slope = 1, intercept = 0) +
  labs(x = 'log Reported FC',
         y = 'log Estimated FC')
```

Correcting bias

```{r}
log_bias <- df_ml |> 
  filter(between(FC_sum, FC_mean-FC_sd, FC_mean+FC_sd)) |> 
  summarise(mean = mean(residual)) |> 
  pull(mean)

print(log_bias)

bias <- exp(log_bias)
print(bias)

df_ml |> 
  filter(between(FC_sum, FC_mean-FC_sd, FC_mean+FC_sd)) |> 
  ggplot(aes(x = total.fc, y = FC_sum*bias)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_abline(slope = 1, intercept = 0) +
  ylim(NA, 10000) +
  labs(x = 'Reported FC',
         y = 'Estimated FC')

df_ml |> 
  filter(between(FC_sum, FC_mean-FC_sd, FC_mean+FC_sd)) |>
  ggplot(aes(x = log(total.fc), y = log(FC_sum) + log_bias)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_abline(slope = 1, intercept = 0) +
  labs(x = 'log Reported FC',
         y = 'log Estimated FC + mean(residual)')
```

```{r}
cor(abs(df_ml$residual), df_ml$distance_difference)
```
