---
title: "Shipping Emissions"
output: html_document
---
```{r}
library(tidyverse)
library(reticulate)
use_python("/usr/bin/python3")
```

# Data Formatting
Monitoring Reporting Verification EU Emissions reports
```{r, child = 'MRV_Data.rmd', eval = TRUE}
```

World Fleet Register
```{r, child = 'WFR_Data.rmd', eval = TRUE}
```

## AIS
```{r, eval = FALSE}
py_run_file('AIS_PreData_Ingest.py')
```

MMSI lists by ship type for subsetting AIS data:
```{r}
load("data/bulkers_WFR.Rda")
bulkers_mmsi <- bulkers_df %>% 
  distinct(MMSI) %>% 
  drop_na() %>% 
  write_csv("data/bulkers_mmsi.csv")

load("data/containerships_WFR.Rda")
containerships_mmsi <- containerships_df %>% 
  distinct(MMSI) %>% 
  drop_na() %>% 
  write_csv("data/containerships_mmsi.csv")
```

```{r, eval = FALSE}
py_run_file('AIS_PreData_Subset.py')
```

High memory requirements, use Compute Canada
```{r, eval = FALSE}
py_run_file('AIS_Data_Index.py')
```

High memory requirements, use Compute Canada
```{r, eval = FALSE}
py_run_file('AIS_Data_Sort.py')
```

```{r, eval = FALSE}
py_run_file('AIS_Data_Combine.py')
```

# Calculations
```{r, eval = TRUE}
py_run_file('AIS_Calculations.py')
```

...files missing...

```{r, eval = FALSE}
py_run_file('AIS_Calculations_TripStats.py')
```

# Data Joining
```{r, child = 'All_Join.rmd', eval = TRUE}
```

# Exploration of composite dataset
```{r, child = 'MRV-WFR_Exploration.rmd', eval = FALSE}
```

# Regressions